name: WGPlayerDamageFlags
main: de.bangl.wgpdf.WGPlayerDamageFlagsPlugin
description: WorldGuard extension to block specific damage types on players in specific regions.
version: 0.3.1

authors: [ BangL ]
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WorldEdit ]
