name: WGPlayerDamageFlags
main: de.bangl.wgpdf.WGPlayerDamageFlags
description: WorldGuard extension to block specific damage types on players in specific regions.
version: 0.1

authors: [ BangL ]
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WorldEdit ]
